{
  "swagger" : "2.0",
  "info" : {
    "version" : "1.2.0",
    "title" : "Sharpener API"
  },
  "host" : "sharpener.ncats.io",
  "basePath" : "/api",
  "schemes" : [ "https" ],
  "paths" : {
    "/create_gene_list" : {
      "post" : {
        "tags" : [ "sharpener" ],
        "summary" : "Create a new gene list",
        "description" : "Creates a new gene list from a collection of gene symbols.",
        "parameters" : [ {
          "in" : "body",
          "name" : "query",
          "description" : "a collection of gene symbols",
          "required" : true,
          "schema" : {
            "type" : "array",
            "items" : {
              "type" : "string"
            },
            "example" : [ "AURA", "TP53" ]
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "successful operation",
            "schema" : {
              "$ref" : "#/definitions/gene_list"
            }
          }
        },
        "x-contentType" : "application/json",
        "x-accepts" : "application/json"
      }
    },
    "/transformers" : {
      "get" : {
        "tags" : [ "sharpener" ],
        "summary" : "Retrieve a list of transformers",
        "description" : "Provides a list of transformers and their descriptions.",
        "parameters" : [ ],
        "responses" : {
          "200" : {
            "description" : "successful operation",
            "schema" : {
              "type" : "array",
              "items" : {
                "$ref" : "#/definitions/transformer_info"
              }
            }
          }
        },
        "x-accepts" : "application/json"
      }
    },
    "/transform" : {
      "post" : {
        "tags" : [ "sharpener" ],
        "summary" : "Transform a gene list",
        "description" : "Depending on the function of a transformer, creates, expands, or filters a gene list.",
        "parameters" : [ {
          "in" : "body",
          "name" : "query",
          "description" : "transformer query",
          "required" : true,
          "schema" : {
            "$ref" : "#/definitions/transformer_query"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "successful operation",
            "schema" : {
              "$ref" : "#/definitions/gene_list"
            }
          }
        },
        "x-contentType" : "application/json",
        "x-accepts" : "application/json"
      }
    },
    "/aggregate" : {
      "post" : {
        "tags" : [ "sharpener" ],
        "summary" : "Aggregate multiple gene lists",
        "description" : "Aggregates multiple gene lists into one gene list.",
        "parameters" : [ {
          "in" : "body",
          "name" : "query",
          "description" : "aggregation query",
          "required" : true,
          "schema" : {
            "$ref" : "#/definitions/aggregation_query"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "successful operation",
            "schema" : {
              "$ref" : "#/definitions/gene_list"
            }
          }
        },
        "x-contentType" : "application/json",
        "x-accepts" : "application/json"
      }
    },
    "/gene_list/{gene_list_id}" : {
      "get" : {
        "tags" : [ "sharpener" ],
        "summary" : "Retrieve a gene list",
        "description" : "Retrieves a gene list for a given gene-list id.",
        "parameters" : [ {
          "name" : "gene_list_id",
          "in" : "path",
          "description" : "gene-list id",
          "required" : true,
          "type" : "string"
        } ],
        "responses" : {
          "200" : {
            "description" : "successful operation",
            "schema" : {
              "$ref" : "#/definitions/gene_list"
            }
          }
        },
        "x-accepts" : "application/json"
      }
    },
    "/submit" : {
      "post" : {
        "tags" : [ "asynchronous" ],
        "summary" : "Asynchronously transform a gene list",
        "description" : "Depending on the function of a transformer, creates, expands, or filters a gene list.",
        "parameters" : [ {
          "in" : "body",
          "name" : "query",
          "description" : "transformer query",
          "required" : true,
          "schema" : {
            "$ref" : "#/definitions/transformer_query"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "successful operation",
            "schema" : {
              "$ref" : "#/definitions/request"
            }
          }
        },
        "x-contentType" : "application/json",
        "x-accepts" : "application/json"
      }
    },
    "/status/{request_id}" : {
      "get" : {
        "tags" : [ "asynchronous" ],
        "summary" : "Get a status of a request",
        "description" : "Get a status of an asynchronous transformation request.",
        "parameters" : [ {
          "name" : "request_id",
          "in" : "path",
          "description" : "Id of an asynchronous transformation request.",
          "required" : true,
          "type" : "string"
        } ],
        "responses" : {
          "200" : {
            "description" : "successful operation",
            "schema" : {
              "$ref" : "#/definitions/request"
            }
          }
        },
        "x-accepts" : "application/json"
      }
    }
  },
  "definitions" : {
    "transformer_query" : {
      "type" : "object",
      "required" : [ "controls", "name" ],
      "properties" : {
        "name" : {
          "type" : "string",
          "description" : "Name of the transformer that will be executed."
        },
        "gene_list_id" : {
          "type" : "string",
          "description" : "Id of the gene list that will be transformed. Required for expanders and filters;  should be ommited for producers."
        },
        "controls" : {
          "type" : "array",
          "description" : "Values that control the behavior of the transformer. Names of the controls must match the names specified in the transformer's definition and values must match types (and possibly  allowed_values) specified in the transformer's definition.",
          "items" : {
            "$ref" : "#/definitions/property"
          }
        }
      },
      "example" : {
        "name" : "MSigDB gene-set producer",
        "controls" : [ {
          "name" : "gene_set_name",
          "value" : "REACTOME_GLUCOSE_TRANSPORT"
        } ]
      }
    },
    "gene_list" : {
      "type" : "object",
      "required" : [ "gene_list_id", "genes", "source" ],
      "properties" : {
        "gene_list_id" : {
          "type" : "string",
          "description" : "Id of the gene list."
        },
        "source" : {
          "type" : "string",
          "description" : "Transformer that produced the gene list."
        },
        "attributes" : {
          "type" : "array",
          "description" : "Additional information and provenance about the gene list.",
          "items" : {
            "$ref" : "#/definitions/attribute"
          }
        },
        "genes" : {
          "type" : "array",
          "description" : "Members of the gene list.",
          "items" : {
            "$ref" : "#/definitions/gene_info"
          }
        }
      },
      "example" : {
        "genes" : [ {
          "identifiers" : {
            "mim" : "MIM:608958",
            "entrez" : "NCBIGene:100",
            "ensembl" : [ "ENSEMBL:ENSG00000196839", "ENSEMBL:ENSG00000196839" ],
            "hgnc" : "HGNC:186",
            "mygene_info" : "100"
          },
          "attributes" : [ {
            "name" : "name",
            "source" : "source",
            "value" : "value"
          }, {
            "name" : "name",
            "source" : "source",
            "value" : "value"
          } ],
          "gene_id" : "gene_id"
        }, {
          "identifiers" : {
            "mim" : "MIM:608958",
            "entrez" : "NCBIGene:100",
            "ensembl" : [ "ENSEMBL:ENSG00000196839", "ENSEMBL:ENSG00000196839" ],
            "hgnc" : "HGNC:186",
            "mygene_info" : "100"
          },
          "attributes" : [ {
            "name" : "name",
            "source" : "source",
            "value" : "value"
          }, {
            "name" : "name",
            "source" : "source",
            "value" : "value"
          } ],
          "gene_id" : "gene_id"
        } ],
        "gene_list_id" : "gene_list_id",
        "attributes" : [ {
          "name" : "name",
          "source" : "source",
          "value" : "value"
        }, {
          "name" : "name",
          "source" : "source",
          "value" : "value"
        } ],
        "source" : "source"
      }
    },
    "gene_info" : {
      "type" : "object",
      "required" : [ "gene_id" ],
      "properties" : {
        "gene_id" : {
          "type" : "string",
          "description" : "Id of the gene. Preferably HGNC id; can be Entrez or ENSEMBL id if HGNC id is not available."
        },
        "identifiers" : {
          "$ref" : "#/definitions/gene_info_identifiers"
        },
        "attributes" : {
          "type" : "array",
          "description" : "Additional information about the gene and provenance about gene-list membership. Sharpener will use myGene.info to add 'gene_symbol', 'synonyms', and 'gene_name' to every gene.  Multiple synonyms are separated by semicolons.",
          "items" : {
            "$ref" : "#/definitions/attribute"
          }
        }
      },
      "example" : {
        "identifiers" : {
          "mim" : "MIM:608958",
          "entrez" : "NCBIGene:100",
          "ensembl" : [ "ENSEMBL:ENSG00000196839", "ENSEMBL:ENSG00000196839" ],
          "hgnc" : "HGNC:186",
          "mygene_info" : "100"
        },
        "attributes" : [ {
          "name" : "name",
          "source" : "source",
          "value" : "value"
        }, {
          "name" : "name",
          "source" : "source",
          "value" : "value"
        } ],
        "gene_id" : "gene_id"
      }
    },
    "attribute" : {
      "type" : "object",
      "required" : [ "name", "value" ],
      "properties" : {
        "name" : {
          "type" : "string"
        },
        "value" : {
          "type" : "string"
        },
        "source" : {
          "type" : "string"
        }
      },
      "example" : {
        "name" : "name",
        "source" : "source",
        "value" : "value"
      }
    },
    "property" : {
      "type" : "object",
      "required" : [ "name", "value" ],
      "properties" : {
        "name" : {
          "type" : "string"
        },
        "value" : {
          "type" : "string"
        }
      }
    },
    "transformer_info" : {
      "type" : "object",
      "required" : [ "function", "name", "status" ],
      "properties" : {
        "name" : {
          "type" : "string",
          "description" : "Name of the transformer."
        },
        "url" : {
          "type" : "string",
          "description" : "Transformers's url."
        },
        "status" : {
          "type" : "string",
          "description" : "Status of the transformer, one of 'online', 'offline'.",
          "enum" : [ "online", "offline" ]
        },
        "function" : {
          "type" : "string",
          "description" : "Function of the transfomer, one of 'producer', 'expander', 'filter'.",
          "enum" : [ "producer", "expander", "filter" ]
        },
        "description" : {
          "type" : "string",
          "description" : "Description of the transformer."
        },
        "parameters" : {
          "type" : "array",
          "description" : "Parameters used to control the transformer.",
          "items" : {
            "$ref" : "#/definitions/parameter"
          }
        },
        "required_attributes" : {
          "type" : "array",
          "description" : "Gene attributes required by the transformer.",
          "items" : {
            "type" : "string"
          }
        }
      },
      "description" : "Definition of the transformer.",
      "example" : {
        "required_attributes" : [ "required_attributes", "required_attributes" ],
        "function" : "producer",
        "name" : "name",
        "description" : "description",
        "parameters" : [ {
          "allowed_values" : [ "allowed_values", "allowed_values" ],
          "default" : "default",
          "name" : "name",
          "suggested_values" : "suggested_values",
          "lookup_url" : "lookup_url",
          "type" : "Boolean"
        }, {
          "allowed_values" : [ "allowed_values", "allowed_values" ],
          "default" : "default",
          "name" : "name",
          "suggested_values" : "suggested_values",
          "lookup_url" : "lookup_url",
          "type" : "Boolean"
        } ],
        "url" : "url",
        "status" : "online"
      }
    },
    "parameter" : {
      "type" : "object",
      "required" : [ "default", "name", "type" ],
      "properties" : {
        "name" : {
          "type" : "string",
          "description" : "Name of the parameter."
        },
        "type" : {
          "type" : "string",
          "description" : "Type of the parameter, one of 'Boolean', 'int', 'double', 'string'.",
          "enum" : [ "Boolean", "int", "double", "string" ]
        },
        "default" : {
          "type" : "string",
          "description" : "Default value of the parameter."
        },
        "allowed_values" : {
          "type" : "array",
          "description" : "Allowed values for the parameter.",
          "items" : {
            "type" : "string"
          }
        },
        "suggested_values" : {
          "type" : "string",
          "description" : "Suggested value range for the parameter."
        },
        "lookup_url" : {
          "type" : "string",
          "description" : "URL to search for suitable parameter values."
        }
      },
      "example" : {
        "allowed_values" : [ "allowed_values", "allowed_values" ],
        "default" : "default",
        "name" : "name",
        "suggested_values" : "suggested_values",
        "lookup_url" : "lookup_url",
        "type" : "Boolean"
      }
    },
    "aggregation_query" : {
      "type" : "object",
      "required" : [ "gene_list_ids", "operation" ],
      "properties" : {
        "operation" : {
          "type" : "string",
          "description" : "Gene-list aggregation operation, one of 'union', 'intersection', 'difference','symmetric difference'."
        },
        "gene_list_ids" : {
          "type" : "array",
          "example" : [ "gene_lis_id_1", "gene_list_id_2" ],
          "description" : "Ids of the gene lists to be aggreagted.",
          "items" : {
            "type" : "string"
          }
        }
      }
    },
    "request" : {
      "type" : "object",
      "required" : [ "request_id", "status" ],
      "properties" : {
        "request_id" : {
          "type" : "string",
          "description" : "Id of the request."
        },
        "status" : {
          "type" : "string",
          "description" : "Status of the request.",
          "enum" : [ "success", "failed", "running" ]
        },
        "gene_list_id" : {
          "type" : "string",
          "description" : "Id of a gene list produced by successful completion this request."
        },
        "current_step" : {
          "type" : "integer",
          "description" : "Current step of the transformation (optional)."
        },
        "total_steps" : {
          "type" : "integer",
          "description" : "Total number of steps in the transformation request (optional)."
        }
      },
      "example" : {
        "gene_list_id" : "gene_list_id",
        "total_steps" : 6,
        "request_id" : "request_id",
        "status" : "success",
        "current_step" : 0
      }
    },
    "gene_info_identifiers" : {
      "properties" : {
        "entrez" : {
          "type" : "string",
          "example" : "NCBIGene:100",
          "description" : "Entrez gene id (CURIE)."
        },
        "hgnc" : {
          "type" : "string",
          "example" : "HGNC:186",
          "description" : "HGNC gene id (CURIE)."
        },
        "mim" : {
          "type" : "string",
          "example" : "MIM:608958",
          "description" : "OMIM gene id (CURIE)."
        },
        "ensembl" : {
          "type" : "array",
          "description" : "ENSEMBL gene id (CURIE).",
          "items" : {
            "type" : "string",
            "example" : "ENSEMBL:ENSG00000196839"
          }
        },
        "mygene_info" : {
          "type" : "string",
          "example" : "100",
          "description" : "myGene.info primary id."
        }
      },
      "example" : {
        "mim" : "MIM:608958",
        "entrez" : "NCBIGene:100",
        "ensembl" : [ "ENSEMBL:ENSG00000196839", "ENSEMBL:ENSG00000196839" ],
        "hgnc" : "HGNC:186",
        "mygene_info" : "100"
      }
    }
  }
}